const books = [
  {
    id: 1,
    title: 'Bumi',
    author: 'Tere Liye',
    year: 2014,
    description: 'Novel ini menceritakan petualangan seorang remaja yang menemukan bahwa dunia tidak sesederhana yang ia kira.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1408339399l/22881267.jpg',
  },
  {
    id: 2,
    title: 'Laskar Pelangi',
    author: 'Andrea Hirata',
    year: 2005,
    description: 'Kisah inspiratif tentang perjuangan sekelompok anak di Belitung untuk mendapatkan pendidikan yang layak.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1359468902l/394711.jpg',
  },
  {
    id: 3,
    title: 'Cantik Itu Luka',
    author: 'Eka Kurniawan',
    year: 2002,
    description: 'Sebuah novel epik yang memadukan sejarah, mitos, dan drama keluarga dalam satu narasi yang kuat.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1425487195l/24933390.jpg',
  },
  {
    id: 4,
    title: 'Pulang',
    author: 'Leila S. Chudori',
    year: 2012,
    description: 'Kisah tentang seorang wartawan Indonesia yang terasing di Paris setelah peristiwa 1965.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1351139702l/16082269.jpg',
  },
  {
    id: 5,
    title: 'Negeri 5 Menara',
    author: 'Ahmad Fuadi',
    year: 2009,
    description: 'Novel yang menginspirasi tentang kehidupan di pondok pesantren dan impian untuk menuntut ilmu hingga ke luar negeri.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1247072551l/6653316.jpg',
  },
  {
    id: 6,
    title: 'Gadis Kretek',
    author: 'Ratih Kumala',
    year: 2012,
    description: 'Sebuah cerita tentang industri kretek di Indonesia yang dibalut dengan kisah cinta dan keluarga.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1618536034l/57793540.jpg',
  },
  {
    id: 7,
    title: 'Aroma Karsa',
    author: 'Dee Lestari',
    year: 2018,
    description: 'Novel fantasi yang mengeksplorasi dunia wewangian dan pencarian jati diri.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1521443419l/39327827.jpg',
  },
  {
    id: 8,
    title: 'Orang-Orang Biasa',
    author: 'Andrea Hirata',
    year: 2019,
    description: 'Sebuah kritik sosial yang dibalut dengan komedi tentang sekelompok orang biasa yang merencanakan kejahatan.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553579045l/44573173.jpg',
  },
  {
    id: 9,
    title: 'Seperti Dendam, Rindu Harus Dibayar Tuntas',
    author: 'Eka Kurniawan',
    year: 2014,
    description: 'Kisah unik tentang seorang jagoan yang impoten dan perjalanan hidupnya yang penuh dengan kekerasan dan cinta.',
    image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1569993883l/48232231.jpg',
  },
];

export default books;